name: Frontend CD

on:
  push:
    branches:
      - main
      - master
  
  workflow_dispatch: 
    

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/gamedock-frontend" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./GameDock.Frontend
          file: ./GameDock.Frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build-and-publish
    runs-on: self-hosted

    steps:
      - name: Deploy frontend
        run: |
          cd /home/ubuntu/gamedock
          docker compose pull frontend
          docker compose up -d frontend
          docker image prune -f